export { default as Home } from './Home'
export { default as About } from './About'
export { default as ContantUs } from './ContantUs'
export { default as Audit } from './Audit'
export { default as Pricing } from './Pricing'